// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// rGmmPeaks
NumericMatrix rGmmPeaks(List data, NumericVector magnitudes, float minMeanPxMag, NumericVector mzAxis);
RcppExport SEXP _rSirem_rGmmPeaks(SEXP dataSEXP, SEXP magnitudesSEXP, SEXP minMeanPxMagSEXP, SEXP mzAxisSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type data(dataSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type magnitudes(magnitudesSEXP);
    Rcpp::traits::input_parameter< float >::type minMeanPxMag(minMeanPxMagSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type mzAxis(mzAxisSEXP);
    rcpp_result_gen = Rcpp::wrap(rGmmPeaks(data, magnitudes, minMeanPxMag, mzAxis));
    return rcpp_result_gen;
END_RCPP
}
// rSirem
List rSirem(NumericMatrix data, NumericMatrix pxCoord, List params, NumericVector scanReference);
RcppExport SEXP _rSirem_rSirem(SEXP dataSEXP, SEXP pxCoordSEXP, SEXP paramsSEXP, SEXP scanReferenceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type data(dataSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type pxCoord(pxCoordSEXP);
    Rcpp::traits::input_parameter< List >::type params(paramsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type scanReference(scanReferenceSEXP);
    rcpp_result_gen = Rcpp::wrap(rSirem(data, pxCoord, params, scanReference));
    return rcpp_result_gen;
END_RCPP
}
// rSiremPeaks
List rSiremPeaks(NumericMatrix data, NumericMatrix pxCoord, List params, NumericVector scanReference);
RcppExport SEXP _rSirem_rSiremPeaks(SEXP dataSEXP, SEXP pxCoordSEXP, SEXP paramsSEXP, SEXP scanReferenceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type data(dataSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type pxCoord(pxCoordSEXP);
    Rcpp::traits::input_parameter< List >::type params(paramsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type scanReference(scanReferenceSEXP);
    rcpp_result_gen = Rcpp::wrap(rSiremPeaks(data, pxCoord, params, scanReference));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_rSirem_rGmmPeaks", (DL_FUNC) &_rSirem_rGmmPeaks, 4},
    {"_rSirem_rSirem", (DL_FUNC) &_rSirem_rSirem, 4},
    {"_rSirem_rSiremPeaks", (DL_FUNC) &_rSirem_rSiremPeaks, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_rSirem(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
