# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rGmmPeaks <- function(data, magnitudes, minMeanPxMag, mzAxis) {
    .Call('_rSirem_rGmmPeaks', PACKAGE = 'rSirem', data, magnitudes, minMeanPxMag, mzAxis)
}

rSirem <- function(data, pxCoord, params, scanReference) {
    .Call('_rSirem_rSirem', PACKAGE = 'rSirem', data, pxCoord, params, scanReference)
}

rSiremPeaks <- function(data, pxCoord, params, scanReference) {
    .Call('_rSirem_rSiremPeaks', PACKAGE = 'rSirem', data, pxCoord, params, scanReference)
}

